export type EgyptianFoodEntry = {
    id: string;
    name: string;
    altNames?: string[];
    calories: number;
    protein: number;
    carbs: number;
    fats: number;
    fiber?: number;
    sugar?: number;
    servingSize?: number;
    servingUnit?: string;
};

// Approximate nutrition values per 100g unless otherwise stated.
export const egyptianFoods: EgyptianFoodEntry[] = [
    {
        id: 'eg-koshari',
        name: 'Koshari',
        altNames: ['Koshary', 'كشري'],
        calories: 190,
        protein: 6,
        carbs: 32,
        fats: 4,
        fiber: 4,
    },
    {
        id: 'eg-ful-medames',
        name: 'Ful Medames',
        altNames: ['Foul Medammes', 'فول مدمس'],
        calories: 110,
        protein: 7,
        carbs: 18,
        fats: 1,
        fiber: 6,
    },
    {
        id: 'eg-taameya',
        name: 'Taameya',
        altNames: ['Egyptian Falafel', 'طعمية'],
        calories: 333,
        protein: 13,
        carbs: 31,
        fats: 18,
        fiber: 8,
    },
    {
        id: 'eg-molokhia',
        name: 'Molokhia',
        altNames: ['Molokheya', 'ملوخية'],
        calories: 70,
        protein: 4,
        carbs: 8,
        fats: 2,
        fiber: 4,
    },
    {
        id: 'eg-mahshi-rice',
        name: 'Mahshi (Rice Stuffed Vegetables)',
        altNames: ['محشي'],
        calories: 165,
        protein: 4,
        carbs: 25,
        fats: 5,
        fiber: 3,
    },
    {
        id: 'eg-bamia-stew',
        name: 'Bamia Stew',
        altNames: ['Okra Stew', 'بامية'],
        calories: 95,
        protein: 3,
        carbs: 9,
        fats: 5,
        fiber: 3,
    },
    {
        id: 'eg-lentil-soup',
        name: 'Egyptian Lentil Soup',
        altNames: ['شوربة عدس'],
        calories: 75,
        protein: 5,
        carbs: 11,
        fats: 1,
        fiber: 3,
    },
    {
        id: 'eg-hawawshi',
        name: 'Hawawshi',
        altNames: ['حواوشي'],
        calories: 290,
        protein: 14,
        carbs: 27,
        fats: 14,
        fiber: 2,
    },
    {
        id: 'eg-feteer-meshaltet',
        name: 'Feteer Meshaltet',
        altNames: ['Egyptian Layered Pie', 'فطير مشلتت'],
        calories: 360,
        protein: 7,
        carbs: 36,
        fats: 21,
        fiber: 1,
    },
    {
        id: 'eg-basmati-rice-cooked',
        name: 'Egyptian Rice (Cooked)',
        altNames: ['رز مصري'],
        calories: 130,
        protein: 2.5,
        carbs: 28,
        fats: 0.3,
        fiber: 0.4,
    },
    {
        id: 'eg-besara',
        name: 'Besara',
        altNames: ['بسارة'],
        calories: 90,
        protein: 6,
        carbs: 12,
        fats: 2,
        fiber: 4,
    },
    {
        id: 'eg-shakshuka',
        name: 'Shakshuka',
        altNames: ['شكشوكة'],
        calories: 120,
        protein: 6,
        carbs: 7,
        fats: 7,
        fiber: 2,
    },
    {
        id: 'eg-grilled-kofta',
        name: 'Grilled Kofta',
        altNames: ['كفتة مشوية'],
        calories: 250,
        protein: 16,
        carbs: 4,
        fats: 18,
    },
    {
        id: 'eg-grilled-kebab',
        name: 'Grilled Kebab',
        altNames: ['كباب مشوي'],
        calories: 275,
        protein: 20,
        carbs: 3,
        fats: 20,
    },
    {
        id: 'eg-sayadeya',
        name: 'Sayadeya Rice with Fish',
        altNames: ['صيادية'],
        calories: 180,
        protein: 12,
        carbs: 17,
        fats: 7,
    },
    {
        id: 'eg-konafa',
        name: 'Konafa',
        altNames: ['Kunafa', 'كنافة'],
        calories: 370,
        protein: 6,
        carbs: 53,
        fats: 14,
        sugar: 30,
    },
    {
        id: 'eg-basbousa',
        name: 'Basbousa',
        altNames: ['بسبوسة'],
        calories: 340,
        protein: 5,
        carbs: 49,
        fats: 13,
        sugar: 32,
    },
    {
        id: 'eg-roz-bel-laban',
        name: 'Roz Bel Laban',
        altNames: ['Rice Pudding', 'رز بلبن'],
        calories: 165,
        protein: 4,
        carbs: 27,
        fats: 4,
        sugar: 14,
    },
    {
        id: 'eg-sobia',
        name: 'Sobia',
        altNames: ['سوبيا'],
        calories: 105,
        protein: 1,
        carbs: 20,
        fats: 2,
        sugar: 16,
        servingSize: 100,
        servingUnit: 'ml',
    },
    {
        id: 'eg-qamar-al-din',
        name: 'Qamar al-Din Juice',
        altNames: ['Apricot Drink', 'قمر الدين'],
        calories: 95,
        protein: 1,
        carbs: 23,
        fats: 0,
        sugar: 20,
        servingSize: 100,
        servingUnit: 'ml',
    },
];
